config/routes.rb
Rails.application.routes.draw do
  mount FloodRiskEngine::Engine => "/"

  root to: "flood_risk_engine/start_forms#new"

  resource :cookies, only: [:edit, :update] do
    member do
      post :accept_analytics
      post :reject_analytics
      post :hide_this_message
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < FloodRiskEngine::ApplicationController
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  helper FloodRiskEngine::ApplicationHelper

  def user_not_authorized(_exception)
    logger.info("Pundit::NotAuthorizedError was raised - attempt to update complete Enrollment")
  end
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  def accept_analytics
    write_cookie(:cookies_policy, :analytics_accepted)
    redirect_back_or_to(root_path)
  end

  def reject_analytics
    write_cookie(:cookies_policy, :analytics_rejected)
    redirect_back_or_to(root_path)
  end

  def hide_this_message
    write_cookie(:cookies_preferences_set, true)
    redirect_back_or_to(root_path)
  end

  def update
    # Google writes the cookies as ".hostname"
    # so we need to state the domain when removing
    cookies.to_hash.each_pair do |k, _v|
      cookies.delete k, domain: ".#{request.hostname}"
    end

    if params[:analytics] == "accept"
      write_cookie(:cookies_policy, :analytics_accepted)
    else
      write_cookie(:cookies_policy, :analytics_rejected)
    end
    write_cookie(:cookies_preferences_set, true)

    redirect_to edit_cookies_path(cookies_updated: true)
  end

  protected

  def write_cookie(name, value)
    cookies[name] =
      {
        value:,
        expires: 1.year
      }
  end
end

app/views/cookies/_action_confirmed.html.erb
<div class="govuk-cookie-banner__message govuk-width-container" role="alert">
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <div class="govuk-cookie-banner__content">
        <p class="govuk-body">
          <% if cookies[:cookies_policy] == "analytics_accepted" %>
            <%= t("cookies-banner.accepted.message") %>
          <% else %>
            <%= t("cookies-banner.rejected.message") %>
          <% end %>
          <%= t(
            "cookies-banner.link.you_can_at_any_time",
            link: link_to(
              t("cookies-banner.link.change_your_cookie_settings"),
              "/cookies/edit",
              class: "govuk-link"
            )
            ).html_safe
          %>
        </p>
      </div>
    </div>
  </div>
  <div class="govuk-button-group">
    <%= button_to t("cookies-banner.button.hide_this_message"),
        main_app.hide_this_message_cookies_path,
        class: "govuk-button"
    %>
  </div>
</div>

app/views/cookies/_action_required.html.erb
<div class="govuk-cookie-banner__message govuk-width-container">
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h2 class="govuk-cookie-banner__heading govuk-heading-m">
        <%= t('cookies-banner.default.heading') %>
      </h2>
      <div class="govuk-cookie-banner__content">
        <p class="govuk-body"><%= t('cookies-banner.default.message_1') %></p>
        <p class="govuk-body"><%= t('cookies-banner.default.message_2') %></p>
      </div>
    </div>
  </div>
  <div class="govuk-button-group">
    <%= button_to t('cookies-banner.button.accept_analytics'),
        main_app.accept_analytics_cookies_path,
        class: "govuk-button"
    %>
    <%= button_to t('cookies-banner.button.reject_analytics'),
        main_app.reject_analytics_cookies_path,
        class: "govuk-button"
    %>
    <%= link_to t('cookies-banner.link.view_cookies'),
        main_app.page_path('cookies'),
        class: "govuk-link"
    %>
  </div>
</div>

app/views/cookies/_banner.html.erb
<% unless cookies[:cookies_preferences_set] %>
  <div class="govuk-cookie-banner " data-nosnippet role="region" aria-label="<%= t('cookies-banner.default.heading') %>">
    <% if cookies[:cookies_policy] %>
    <%= render partial: "cookies/action_confirmed" %>
    <% else %>
    <%= render partial: "cookies/action_required" %>
    <% end %>
  </div>
<% end %>

app/views/cookies/edit.html.erb
<%= render("flood_risk_engine/shared/back", back_path: main_app.page_path("cookies")) %>
<% if params[:cookies_updated] %>
  <div class="govuk-notification-banner govuk-notification-banner--success" role="alert" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
    <div class="govuk-notification-banner__header">
      <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
        <%= t('.updated.success') %>
      </h2>
    </div>
    <div class="govuk-notification-banner__content">
      <p class="govuk-notification-banner__heading">
        <%= t('.updated.you_set_your_cookie_preferences') %>
      </p>
    </div>
  </div>
<% end %>

<%= form_tag cookies_path, method: :patch do %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <h1 class="govuk-heading-l"><%= t('.heading') %></h1>
      <p class="govuk-body"><%= t('.text_1') %></p>
      <p class="govuk-body"><%= t('.text_2') %></p>
      <h2 class="govuk-heading-m"><%= t('.cookie_settings.subheading') %></h2>
      <p class="govuk-body"><%= t('.cookie_settings.text_1') %></p>
      <div class="govuk-form-group">
      <fieldset class="govuk-fieldset">
        <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
          <h2 class="govuk-heading-m"><%= t('.analytics_cookies.subheading') %></h2>
          <p class="govuk-body"><%= t('.analytics_cookies.text_1') %></p>
          <p class="govuk-body"><%= t('.analytics_cookies.text_2') %></p>
          <ul class="govuk-list govuk-list--bullet">
            <li><%= t('.analytics_cookies.list_item_1') %></li>
            <li><%= t('.analytics_cookies.list_item_2') %></li>
            <li><%= t('.analytics_cookies.list_item_3') %></li>
          </ul>
        </legend>
        <div class="govuk-radios">
          <div class="govuk-radios__item">
            <%= radio_button_tag :analytics, :accept,
                (cookies[:cookies_policy] && cookies[:cookies_policy] == "analytics_accepted"),
                class: "govuk-radios__input" %>
            <%= label_tag :analytics_accept,
                t('.analytics_cookies.radio_button_label.accept'),
                class: "govuk-label govuk-radios__label" %>
          </div>
          <div class="govuk-radios__item">
            <%= radio_button_tag :analytics, :reject,
                !(cookies[:cookies_policy] && cookies[:cookies_policy] == "analytics_accepted"),
                class: "govuk-radios__input" %>
            <%= label_tag :analytics_reject,
                t('.analytics_cookies.radio_button_label.reject'),
                class: "govuk-label govuk-radios__label" %>
          </div>
        </div>
      </fieldset>
    </div>
    <h2 class="govuk-heading-m"><%= t('.essential_cookies.subheading') %></h2>
    <p class="govuk-body"><%= t('.essential_cookies.text_1') %></p>
    <p class="govuk-body"><%= t('.essential_cookies.text_2') %></p>
    <p class="govuk-body"><%= link_to t('.find_out_more.text'), t('.find_out_more.url') %></p>
    <%= submit_tag t('.submit_button'), class: "govuk-button" %>
  </div>
<% end %>

app/views/flood_risk_engine/enrollments/states/_add_exemptions.html.erb
  




  

  

  <div class="grid-row">
    <div class="column-two-thirds">


      <header class="text">
    <h1 class="form-title heading-large" id="groupLabel">
      <%= set_page_title t('.heading') %>
    </h1>
  </header>


      <p class="panel panel-border-wide"><%= t('.para_text') %> <%= link_to 'Exempt flood risk activities guidance', 'environmental-permitting-regulations-exempt-flood-risk-activities_url', target: 'blank' %> <%= t('.para_text1') %></p>

      <%= form.fields_for @form.model do |f| %>


        <style>
          span.exmpt{
            font-weight:bold;
            float:right;
          }

        label.exemption{
          background-color:#ededed;
          border-color:#ededed;
        }

        @media screen and (min-width: 320px) {
          label.exemption{
            width:99%;
            }
        }

        </style>

        <div class="form-group">
          <fieldset>
            <legend class="visuallyhidden"><%= t('.legend') %></legend>



            <table summary="exemption-codes" role="presentation" class="exemption-table">
              <thead>
              <tr>
                <th class="exemption-description"><span class="heading-small"><%= t('.text') %></span></th>
                <th class="exemption-description"><span class="heading-small"><%= t('.text1') %></span></th>
                <th class="exemption-checkbox"><span class="heading-small"><%= t('.text2') %></span></th>
              </tr>
              </thead>
              <tbody>
              <% @form.exemptions.each do |a| %>
                <tr>
                  <td class="exemption-description">
                    <span class="bold-large"><%= a.code %></span>
                  </td>
                  <td class="exemption-description">
                    <p><%= a.summary %></p>
                  </td>
                  <td class="exemption-select">
                    <label class="form-checkbox" for="checkbox-<%= a.code %>">
                      <%= f.radio_button 'add_exemptions_id',
                                         a.id,
                                         checked: false,
                                         id: "a"
                      %>
                      <%= a.display %>
                    </label>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
        

          <p><%= t('.para_text2') %></p>

          </fieldset>
        </div>
<!-- // end .form-group -->

        

      <% end %>

    </div>
  </div>

app/views/flood_risk_engine/enrollments/states/_check_exemptions.html.erb
  

  

  <%= form.fields_for @form.model do |f| %>

      <header class="text">
    <h1 class="form-title heading-large" id="groupLabel">
      <%= set_page_title t('.heading') %>
    </h1>
  </header>


    <table class="check-your-answers">
      <tbody>
        <tr>
          <th>
            <p class="font-small"><%= t('.para_text') %></p>
          </th>
          <td>
            <span class="bold-small"><%= t('.text') %></span>
          </td>
          <td class="change-answer">
            <%= link_to 'Change exemption FRA5', 'add_exemptions_url' %>
          </td>
        </tr>

        <tr>
          <th>
            <p class="font-small"><%= t('.para_text1') %></p>
          </th>
          <td>
            <span class="bold-small"><%= t('.text1') %></span>
          </td>
          <td class="change-answer">
            <%= link_to 'Change  exemption FRA9', 'add_exemptions_url' %>
          </td>
        </tr>
      </tbody>
    </table>

    <br>

    <div class="form-group">
      <%= link_to 'Add another exemption', 'add_exemptions_url' %>
    </div>

    

  <% end %>

app/views/flood_risk_engine/enrollments/states/_check_location.html.erb
<fieldset>

  <legend class="visuallyhidden"><%= t('.legend') %></legend>

  <div class="panel panel-border-wide">
    <p class="text"><%= t('.para_text') %></p>

    <ul class="list list-bullet">
      <li><%= t('.list_item') %></li>
      <li><%= t('.list_item1') %></li>
      <li><%= t('.list_item2') %></li>
    </ul>

    <p class="text"><%= t('.para_text1') %></p>

  </div>

  <br>

  <%= form_group_and_validation(form, :base) do %>
    <div class="form-group">
      <label class="block-label" for="location_check_yes">
        <%= f.radio_button :location_check, :yes, { checked: false, :class => "radio", id: "yes_option" } %>
        <%= t('.label') %>
      </label>

      <label class="block-label" for="location_check_no">
        <%= f.radio_button :location_check, :no, { checked: false, :class => "radio", id: "no_option" } %>
        <%= t '.label1' %>
      </label>
  <% end %>
</div>

</fieldset>

app/views/flood_risk_engine/enrollments/states/_grid_reference.html.erb
  
  <%= form.fields_for @form.model do |f| %>

    

    <div class="grid-row">
      <div class="column-two-thirds">

          <header class="text">
    <h1 class="form-title heading-large" id="groupLabel">
      <%= set_page_title t('.heading') %>
    </h1>
  </header>


        <fieldset>
          <legend class="visuallyhidden"><%= t('.legend') %></legend>

          <!-- Grid reference -->
          <div class="form-group">
            <label class="form-label" for="grid-reference"><%= t('.label') %></label>
            <p class="form-hint"><%= t('.para_text') %></p>
                      <%= f.text_field 'grid_reference', class:  'form-control' %>

          </div>

          <!-- Find grid reference -->
          <details style="padding-bottom: 18px;">
            <summary><span class="summary"><%= t('.text') %></span></summary>
            <div class="panel panel-border-narrow">
              <p><%= t('.para_text1') %> <%= link_to 'Ordnance Survey online map', 'osmaps_url' %> <%= t('.para_text2') %></p>
              <p><%= t('.para_text3') %></p>
            </div>
          </details>

        </fieldset>

        <!-- Primary button -->
        

      </div>
    </div>

  <% end %>

app/views/flood_risk_engine/enrollments/states/_local_authority.html.erb
<div class="grid-row">
  <div class="column-two-thirds">

    <%= form.fields_for @form.model do |f| %>

      <header class="text">
        <h1 class="form-title heading-large" id="groupLabel">
          <%= set_page_title t('.heading') %>
        </h1>
      </header>

      <fieldset>
        <legend class="visuallyhidden"><%= t('.legend') %></legend>

        <!-- Local authority name -->
        <div class="form-group">
          <label class="form-label" for="authority-name"><%= t('.label') %></label>
          <p class="form-hint"><%= t('.para_text') %></p>
          <%#TODO: what is this field ? organisation.name ? = f.text_field 'authority_name', class:  'form-control' %>
        </div>
      </fieldset>

    <% end %>

  </div>
</div>

app/views/flood_risk_engine/enrollments/states/_local_authority_postcode.html.erb
  

  

  <div class="grid-row">
    <div class="column-two-thirds">

      <%= form.fields_for @form.model do |f| %>

          <header class="text">
    <h1 class="form-title heading-large" id="groupLabel">
      <%= set_page_title t('.heading') %>
    </h1>
  </header>


        <fieldset>
          <legend class="visuallyhidden"><%= t('.legend') %></legend>

          <!-- Postcode look-up -->
          <div class="form-group">
            <label class="form-label" for="postcode"><%= t('.label') %></label>
            <span class="form-hint"><%= t('.text') %></span>
                      <%= f.text_field 'postcode', class:  'form-control' %>

          </div>

        </fieldset>

        <!-- Show and hide address-->
        <details>
          <summary id="show-hide-details-summary-0" aria controls="details-content-0" tabindex="0" aria-controls="details-content-0" role="button">
            <span class="summary"><%= t('.text1') %></span>
          </summary>
          <span style="display:block" class="panel-indent" id="details-content-0"></span>

          <br>

          <!-- Manual entered address -->
          <div class="form-group">
            <label class="form-label" for="premises"><%= t('.label1') %></label>
            <div class="form-hint"><%= t('.div_text9') %></div>
                      <%= f.text_field 'premises', class:  'form-control' %>

          </div>

          <div class="form-group">
            <label class="form-label" for="street_address"><%= t('.label2') %></label>
                      <%= f.text_field 'street_address', class:  'form-control' %>

          </div>

          <div class="form-group">
            <label class="form-label" for="locality"><%= t('.label3') %></label>
                      <%= f.text_field 'locality', class:  'form-control' %>

          </div>

          <div class="form-group">
            <label class="form-label" for="city"><%= t('.label4') %></label>
                      <%= f.text_field 'city', class:  'form-control' %>

          </div>

          <div class="form-group">
            <label class="form-label" for="manual-postcode"><%= t('.label5') %></label>
                      <%= f.text_field 'manual_postcode', class:  'form-control' %>

          </div>

        </details>

        <br>

        <!-- Primary button -->
        

      <% end %>

    </div>
  </div>

app/views/flood_risk_engine/enrollments/states/_organisation_type.html.erb
  

  

  <div class="grid-row">
    <div class="column-two-thirds">

      <%= form.fields_for @form.model do |f| %>

          <header class="text">
    <h1 class="form-title heading-large" id="groupLabel">
      <%= set_page_title t('.heading') %>
    </h1>
  </header>


        <div class="form-group">
          <fieldset>
<%=  f.label :local_authorityoption_label, for: 'local_authority', :class => 'block-label' do %>
 <%= f.radio_button :who_is_legally_responsible_for_the_activity?, 'local_authority', checked: false, id: 'local_authority' %>
 <%= t 'local_authority_option' %>
<% end %>

<%=  f.label :limited_companyoption_label, for: 'limited_company', :class => 'block-label' do %>
 <%= f.radio_button :who_is_legally_responsible_for_the_activity?, 'limited_company', checked: false, id: 'limited_company' %>
 <%= t 'limited_company_option' %>
<% end %>

<%=  f.label :limited_liabilityoption_label, for: 'limited_liability', :class => 'block-label' do %>
 <%= f.radio_button :who_is_legally_responsible_for_the_activity?, 'limited_liability', checked: false, id: 'limited_liability' %>
 <%= t 'limited_liability_option' %>
<% end %>

<%=  f.label :individualoption_label, for: 'individual', :class => 'block-label' do %>
 <%= f.radio_button :who_is_legally_responsible_for_the_activity?, 'individual', checked: false, id: 'individual' %>
 <%= t 'individual_option' %>
<% end %>

<%=  f.label :partnershipoption_label, for: 'partnership', :class => 'block-label' do %>
 <%= f.radio_button :who_is_legally_responsible_for_the_activity?, 'partnership', checked: false, id: 'partnership' %>
 <%= t 'partnership_option' %>
<% end %>

<%=  f.label :otheroption_label, for: 'other', :class => 'block-label' do %>
 <%= f.radio_button :who_is_legally_responsible_for_the_activity?, 'other', checked: false, id: 'other' %>
 <%= t 'other_option' %>
<% end %>

<%=  f.label :not_knownoption_label, for: 'not_known', :class => 'block-label' do %>
 <%= f.radio_button :who_is_legally_responsible_for_the_activity?, 'not_known', checked: false, id: 'not_known' %>
 <%= t 'not_known_option' %>
<% end %>
</fieldset>
        </div>

        <details style="padding-bottom: 18px;">
          <summary><span class="summary"><%= t('.text') %></span></summary>
          <div class="panel panel-border-narrow">
            <p><%= t('.para_text') %></p>
            <p><%= t('.para_text1') %></p>

            <ul class="list-bullet">
              <li><%= t('.list_item') %></li>
              <li><%= t('.list_item1') %></li>
              <li><%= t('.list_item2') %></li>
              <li><%= t('.list_item3') %></li>
              <li><%= t('.list_item4') %></li>
              <li><%= t('.list_item5') %></li>
            </ul>
          </div>
        </details>

        

      <% end %>

    </div>
  </div>

app/views/flood_risk_engine/enrollments/states/_unregistered.html.erb
  <div class="grid-row">
    <div class="column-two-thirds">

        <header class="text">
    <h1 class="form-title heading-large" id="groupLabel">
      <%= set_page_title t('.heading') %>
    </h1>
  </header>


      <h2 class="heading-medium">Before you start</h2>

      <ul class="list list-number">
        <li><%= t('.list_item1') %> <%= link_to 'flood risk activities guidance', "" %> <%= t('.list_item2') %></li>
        <li><%= t('.list_item3') %></li>
        <li><%= t('.list_item4') %></li>
        <li><%= t('.list_item5') %></li>
      </ul>

      <p><%= t('.para_text') %></p>

      <p> <%#= link_to 'Start now', check_location_url(@enrollment), class: 'button button-start', role: 'button' %> </p>

      <p><%= t('.para_text1') %></p>

      <ul class="list list-bullet">
        <li><%= t('.list_item6') %></li>
        <li><%= t('.list_item7') %></li>
        <li><%= t('.list_item8') %></li>
        <li><%= t('.list_item9') %></li>
        <li><%= t('.list_item10') %></li>
      </ul>

      <div class="contact">
        <h3 class="heading-medium">Contact the Environment Agency</h3>
        <%#= link_to 'enquiries@environment-agency.gov.uk', mailto:enquiries@environment-agency.gov.uk_url(@enrollment) %>
        <br><%= t('.div_text16') %><br><%= t('.div_text17') %><br><%= t('.div_text18') %>
</div>

    </div>
    <div class="column-third">

      <aside class="govuk-related-items" role="complementary">
        <h2 class="heading-medium" id="subsection-title">Flood risk activities</h2>
        <nav role="navigation" aria-labelledby="subsection-title">
          <ul class="font-xsmall">
            <li> <%= link_to 'Flood risk activities guidance', "" %> </li>
            <li> <%= link_to 'More in Subsection', "", class: 'bold-xsmall' %> </li>
          </ul>
        </nav>
      </aside>

    </div>
  </div>

app/views/layouts/application.html.erb
<% content_for :cookies_banner do %>
  <%= render partial: "cookies/banner" %>
<% end %>

<% content_for :head do %>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render "shared/google_analytics" if ENV["GOOGLE_ANALYTICS_ID"].present? %>
<% end %>

<% content_for :page_title, title %>

<% content_for :header_content do %>
  <%= link_to  t(:global_proposition_header), main_app.root_path, id: "proposition-name", class: "govuk-header__link govuk-header__service-name" %>
<% end %>

<% content_for :phase_banner do %>
  <div class="govuk-phase-banner">
    <p class="govuk-phase-banner__content">
      <strong class="govuk-tag govuk-phase-banner__content__tag">
        <%= t(".beta")  %>
      </strong>
      <span class="govuk-phase-banner__text">
        <%= t(
              ".feedback",
              link: link_to(
                t(".feedback_link.text"),
                t(".feedback_link.url"),
                class: "govuk-link",
                target: "_blank"
              )
            ).html_safe
        %>
      </span>
    </p>
  </div>
<% end %>

<% content_for :footer do %>
  <ul class="govuk-footer__inline-list">
    <li class="govuk-footer__inline-list-item">
       <%= t('flood_risk_engine.shared.footer.support_text') %>
       <%= link_to t("flood_risk_engine.shared.footer.helpline_telephone_number"),
        "tel:#{t "flood_risk_engine.shared.footer.helpline_telephone_number_uri" }",
        class: "govuk-footer__link" %>
    </li>
  </ul>

  <h2 class="govuk-visually-hidden">Support links</h2>
  <ul class="govuk-footer__inline-list">
    <li class="govuk-footer__inline-list-item">
      <%= link_to 'Privacy', main_app.page_path('privacy_notice'), class: "govuk-footer__link" %>
    </li>
    <li class="govuk-footer__inline-list-item">
      <%= link_to 'Cookies', main_app.page_path('cookies'), class: "govuk-footer__link" %>
    </li>
    <li class="govuk-footer__inline-list-item">
      <%= link_to 'Accessibility', main_app.page_path('accessibility'), class: "govuk-footer__link" %>
    </li>
  </ul>
<% end %>

<%= render template: "layouts/defra_ruby_template" %>

app/views/pages/accessibility.html.erb
<% content_for :title, "Accessibility statement" %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l">
      Accessibility statement
    </h1>

    <h2 class="govuk-heading-m">
      Using this website
    </h2>
    <p class="govuk-body">
      The Register a Flood Risk Activity Exemption service is run by the Environment Agency. We want as many people as possible to be able to use this website. For example, that means you should be able to:
    </p>
    <ul class="govuk-list govuk-list--bullet">
      <li>change colours, contrast levels and fonts</li>
      <li>zoom in up to 200% without the text spilling off the screen</li>
      <li>navigate most of the website using just a keyboard</li>
      <li>navigate most of the website using speech recognition software</li>
      <li>listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)</li>
    </ul>

    <p class="govuk-body">
      We have also made the website text as simple as possible to understand.
    </p>

    <p class="govuk-body">
      <a href="https://mcmw.abilitynet.org.uk/">AbilityNet</a> has advice on making your device easier to use if you have a disability.
    </p>

    <h2 class="govuk-heading-m">
      How accessible this website is
    </h2>
    <p class="govuk-body">
      This website is fully accessible.
    </p>

    <h2 class="govuk-heading-m">
      What to do if you cannot access parts of this website
    </h2>
    <p class="govuk-body">
      If you need information on this website in large print or braille:
    </p>
    <ul class="govuk-list govuk-list--bullet">
      <li>email <a href="mailto:enquiries@environment-agency.gov.uk">enquiries@environment-agency.gov.uk</a>
      <li>call us on 03708 506 506 (Monday to Friday, 8am to 6pm)</li>
    </ul>
    <p class="govuk-body">
      We will consider your request and get back to you within 10 days.
    </p>

    <h2 class="govuk-heading-m">
      Reporting accessibility problems with this website
    </h2>
    <p class="govuk-body">
    We are always looking to improve the accessibility of this website. If you find any problems that are not listed on this page or think we are not meeting the requirements of the accessibility regulations, contact:
    </p>
    <ul class="govuk-list govuklist--bullet">
      <li>email <a href="mailto:enquiries@environment-agency.gov.uk">enquiries@environment-agency.gov.uk</a>
      <li>call us on 03708 506 506 (Monday to Friday, 8am to 6pm)</li>
    </ul>

    <h2 class="govuk-heading-m">
      Enforcement procedure
    </h2>
    <p class="govuk-body">
      The Equality and Human Rights Commission (EHRC) is responsible for enforcing the accessibility regulations. If you are not happy with how we respond to your complaint, contact the <a href="https://www.equalityadvisoryservice.com/">Equality Advisory and Support Service (EASS)</a>.
    </p>

    <h2 class="govuk-heading-m">
      Contacting us by phone or visiting us in person
    </h2>
    <p class="govuk-body">
    We do not currently have a text relay service for people who are deaf, hearing impaired or have a speech impediment. You can contact us by:
    </p>
    <ul class="govuk-list govuk-list--bullet">
      <li>phone on 03708 506 506 (Monday to Friday, 8am to 6pm)</li>
      <li>email at <a href="mailto:enquiries@environment-agency.gov.uk">enquiries@environment-agency.gov.uk</a>
      <li>Twitter <a href="https://twitter.com/envagency">@envagency</a></li>
      <li>Facebook <a href="https://www.facebook.com/environmentagency">@environmentagency</a></li>
    </ul>
    <p class="govuk-body">
      If you visit our offices and need assistance or an interpreter, you should contact us before you visit.
    </p>
    <p class="govuk-body">
      <a href="https://www.gov.uk/government/organisations/environment-agency/about/access-and-opening">Visiting our offices.</a>
    </p>

    <h2 class="govuk-heading-m">
      Technical information about this website’s accessibility
    </h2>
    <p class="govuk-body">
      The Environment Agency is committed to making its website accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.
    </p>

    <h2 class="govuk-heading-m">
      Compliance status
    </h2>
    <p class="govuk-body">
      This service is fully compliant with the <a href="https://www.w3.org/TR/WCAG21/">Web Content Accessibility Guidelines version 2.1</a> AA standard.
    </p>

    <h2 class="govuk-heading-m">
      How we tested this website
    </h2>

    <p class="govuk-body">
      The service was last tested on 10th April 2023 and was checked for compliance with WCAG 2.1 AA.
    </p>

    <p class="govuk-body">
      It was tested by the Flood Risk Activity Exemptions development team, and the non-compliant elements will be included in the ongoing development work.
    </p>

    <p class="govuk-body">
      This statement was prepared on 19th May 2023.
    </p>
  </div>
</div>

app/views/shared/_google_analytics.erb
<% if cookies[:cookies_policy] == "analytics_accepted" %>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','<%= ENV["GOOGLE_ANALYTICS_ID"] %>');</script>
<!-- End Google Tag Manager -->
<% end %>